ecomapp/urls.py
from django.urls import path
from .import views
from .import api
app_name='ecomapp'
urlpatterns=[
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
 	#url from apis
 	path('api/product',api.product_list_api,name='product_list_api'),
 	path('api/<int:id>',api.product_detail,name='product_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/' ,include('order.urls',namespace='orders')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('stor/',include('ecomapp.urls',namespace='ecomapp')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('api-auth/', include('rest_framework.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8" />
 <title>{% block title %}My shop{% endblock %}</title>
 <link href="{% static "css/base.css" %}" rel="stylesheet">
 <script src="{% static 'js/main.js'%}" defer></script>
</head>

 <body>
 
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url "ecomapp:product_list"%}" class="logo"">Hexa</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "ecomapp:product_list"%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "ecomapp:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %} 
    </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET">
      
      <input id="search_here" class="form-control" placeholder="type here to search"/>
       <div id='box'>
         {% for item in products %}
           {{item.name}}<br>
         {% endfor %}
       </div>
    </form>
  </div>
</nav>

 <div id="subheader">
 <div class="cart">
   {% with total_items=cart|length %}
      {% if total_items > 0 %}
    Your Cart:
    <a href="{% url "cart:cart_detail" %}">
      {{ total_items}} item{{total_items|pluralize}} {{cart.get_total_price}} $
    </a>
  {% else %}
    Your Cart is empty.
{% endif %}
{% endwith %}
 </div>

 </div>
 <div id="content">
 {% block content %}
 {% endblock %}

   {% block scripts %}
     <script >
       const data ='{{products}}';
       console.log(data);

       const rdata=JSON.parse(data.replace(/&quot;/g,','))
       console.log(rdata)
       const input = document.getElementById('search_here');
       console.log(input.value)
       let filtereArr=[]
       input.addEventListener('keyup',()=>{
        box.innerHTML=""
       })

      
     </script>
 {% endblock scripts %}

 </div>
 
 </body>
</html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>